CSHARP-3056: Minimize chances of tests timing out at completion
vincentkam/mongo-csharp-driver pull request #105
Opened 2020-04-11 15:51 UTC by vincentkam

https://jira.mongodb.org/browse/CSHARP-3056

We're seeing tests pass and then seemingly fail during the "echo" command.
This PR removes the echo command to see if this will help.

2020-04-11 16:02 UTC, rstam commented
Seems unlikely that removing an echo command would make any difference.

Do you need to start an Evergreen patch build to see if helps?

2020-04-11 23:38 UTC, vincentkam commented
Anecdotally, I submitted a patch for the spec auth with 3 variants and all 3 timed out during the echo command. Removing the echo command (and running a full patch with all variants), I saw ~3 tasks time out.

I've started a pair of patch builds: one with this fix and one off master and will post the results when they finish :)

At the very least, removing the echo statement should be neutral. I have a vague hypothesis that EG for some reason dislikes extra commands after the command to run our tests, but admit it's just an idea that spawned out of my unfortunate patch build where 100% of the variants (3 out of 3) timed out at the echo command :)

2020-04-12 16:43 UTC, rstam requested changes
Waiting for you to report back on your Evergreen tests before approving this pull request.

Please re-request a review when you are ready.

2020-04-13 14:03 UTC, DmitryLukyanov commented
This change looks really suspicions :)

2020-04-13 15:22 UTC, jyemin commented
If this is really a thing, at the least it should generate an Evergreen ticket to report what would be a really serious bug.  

But it seems unlikely that it's really a bug.

2020-04-13 21:27 UTC, vincentkam commented
Quick informal test:

Master: 26 red in initial red, 6 reds due to timeouts at the "Skipping cert removal" echo line. 

With the patch: 19 red, 4 of which happen at the "Finished executing task: Test" stage, which is the that prints right before the "Skipping cert removal" line would be echoed if it still existed. 

Given that wasn't a drastic reduction in timeouts,  I'm fine with closing this PR, unless others object.

2020-04-13 21:27 UTC, closed without merging