CSHARP-2285
vincentkam/mongo-csharp-driver pull request #4
Opened 2018-05-31 22:50 UTC by vincentkam

Update Feature class to include when features stop being supported.
Disable group command tests.

2018-05-31 23:59 UTC, rstam reviewed
Check Evergreen.

There are a few more tests that still need to be skipped.

2018-05-31 23:59 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/GroupOperationTests.cs
> +            RequireServer.Check().Supports(Feature.GroupCommand).Supports(Feature.Collation);
Supports accepts multiple features. You can use:

    ...Suports(Feature.GroupCommand, Feature.Collation);

2018-05-31 23:59 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/GroupOperationTests.cs
> +            RequireServer.Check().Supports(Feature.GroupCommand).Supports(Feature.FailPoints).ClusterTypes(ClusterType.Standalone, ClusterType.ReplicaSet);
You can combine the two calls to Support.

2018-06-01 02:13 UTC, vincentkam commented
Disabled some additional tests, waiting on Evergreen.

2018-06-01 13:40 UTC, rstam requested changes

2018-06-01 13:40 UTC, rstam commented on tests/MongoDB.Driver.Legacy.Tests/MongoCollectionTests.cs
>          [Fact]
Needs to be [SkippableFact]

2018-06-01 13:40 UTC, rstam commented on tests/MongoDB.Driver.Legacy.Tests/MongoCollectionTests.cs
>          [Fact]
Needs to be [SkippableFact]

Look for all of them. I won't add a comment to each one...

2018-06-01 18:00 UTC, rstam commented
Notify me once Evergreen is green (or only failing on unrelated tests) and I'll lgtm this.

2018-06-04 14:38 UTC, vincentkam commented
Green except for the expected errors: https://evergreen.mongodb.com/version/5b118d53e3c3314e54f0479d

2018-06-04 15:28 UTC, rstam approved these changes

2018-06-04 18:07 UTC, merged